encurtador/urls.py
from django.urls import path, re_path
from . import views

app_name = 'encurtador'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    re_path(r'^(?P<uuid_curto>[\-\d\w]+)$',
                    views.GoToRedirectView.as_view()),

    path('my-links/',
                    views.MyLinksListView.as_view(), name='my_links'),
]

encurtador_de_link/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('encurtador.urls')),
    path('perfil/', include('perfil.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/urls.py
  
from django.urls import path, re_path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('acessos/', views.ProgressaoAcesso.as_view(), name='acessos'),
    # re_path(r'^pdf/$', views.GenerateRelatorioPdfAcessos.as_view(), name="relatorio"),
    path('relatorio/', views.GenerateRelatorioPdfAcessos.as_view(), name="relatorio"),
]

encurtador/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from .util import UUIDCurto


class LinkManager(models.Manager):
    def by_uuid(self, uuid):
        return self.filter(pk=models.Link.decodificar_uuid(uuid)).get()

    def meus_links(self, usuario):
        return self.filter(usuario=usuario)


class Link(models.Model):
    handler = UUIDCurto()
    url = models.URLField()
    criacao = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    objects = LinkManager()
    # acessos = models.PositiveIntegerField(default=0)

    @property
    def uuid(self):
        return self.handler.codificar(self.pk)

    @classmethod
    def decodificar_uuid(self, uuid):
        return self.handler.decodificar(uuid)

    @property
    def url_curta(self):
        return settings.ENCURTADOR_SITE_BASE_URL + self.uuid

    def __unicode__(self):
        return self.url

    class Meta:
        ordering = ['-criacao']
        get_latest_by = 'criacao'

encurtador/forms.py
# coding:utf-8
from django.forms import ModelForm, TextInput, URLField
from .models import Link


class EncurtarURLForm(ModelForm):
    url = URLField(widget=TextInput(attrs={
        'placeholder': 'Entre com a URL que deseja encurtar...',
    }))

    class Meta:
        model = Link
        fields = ['usuario']

encurtador/views.py
# coding:utf-8
from django.views import View
from django.views.generic import RedirectView, ListView
from django.template.response import TemplateResponse
from django.views.defaults import page_not_found
from django.http import HttpResponse
import simplejson
from urllib.request import urlopen
from perfil.views import LoginRequiredMixin
from . import models
from . import forms

class Home(View):
    template_name = 'encurtador/home.html'

    def get(self, request, *args, **kwargs):
        contexto = self.get_context_data()
        return TemplateResponse(
            request=self.request,
            template=self.template_name,
            context=contexto,
            **kwargs
        )

    def post(self, request, *args, **kwargs):
        contexto = self.get_context_data()
        q = request.POST

        if self.request.user.is_authenticated:
            q = q.copy()
            q[u'usuario'] = request.user.pk

        form = forms.EncurtarURLForm(q)
        resultado = {}

        if form.is_valid():
            link = form.save()
            resultado['status'] = 'ok'
            resultado['url'] = link.url
            resultado['url_curta'] = link.url_curta
        else:
            resultado['status'] = 'erro'
            resultado['mensagem'] = 'Informe uma URL válida para ser encurtada!'
        contexto['resultado'] = resultado

        if self.request.is_ajax():
            json = simplejson.dumps(resultado)
            return HttpResponse(json, content_type='application/json')

        return TemplateResponse(
            request=self.request,
            template=self.template_name,
            context=contexto,
            **kwargs
        )

    def get_context_data(self, **kwargs):
        contexto = {}
        contexto['form_encurtar_url'] = forms.EncurtarURLForm
        return contexto


class GoToRedirectView(RedirectView):
    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid_curto')
        try:
            l = models.Link.objects.by_uuid(uuid)
            self.url = urlopen.unquote(l.url)
            return super(GoToRedirectView, self).get(request, *args, **kwargs)
        except models.Link.DoesNotExist:
            return page_not_found(request)


class MyLinksListView(LoginRequiredMixin, ListView):
    template_name = 'encurtador/my-links.html'
    context_object_name = 'meus_links'
    paginate_by = 10

    def get_queryset(self):
        self.queryset = models.Link.objects.meus_links(self.request.user)
        return super(MyLinksListView, self).get_queryset()

encurtador/templates/encurtador/home.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}Home | {% endblock %}


<link rel="stylesheet" href="{% static 'encurtador/css/home.css' %}" type="text/css">


{% block conteudo %}
    <div id="home-container">
        <div id="logo">
            <h1>
                <a href="{% url 'encurtador:home' %}">
                    <img src="{% static 'encurtador/img/logo-home.png' %}" alt="dShortener - encurtador de URLs">
                </a>
                <p>dShortener - Um encurtador de URLs feito em Django</p>
                <p class="clipboard-info"></p>
            </h1>
        </div>
        {% if user.is_authenticated %}
        <div id="form-shorten-url">
            <form action="" method="post">
                {% csrf_token %}
                <label>{{ form_encurtar_url.url }}</label>
                <input type="submit" id="shorten-it" value="Encurtar">
            </form>
        </div>
        <ul id="shortened-urls" class="{{ resultado.status }} {% if resultado.status %}show{% endif %}">
            {% ifequal resultado.status 'ok' %}
            <li class="short-url">
                <span class="select-text" data-shortened-url="{{ resultado.url_curta }}">selecionar</span> - <input type="text" data-clipboard-text="{{ resultado.url_curta }}" value="{{ resultado.url_curta }}" title="Clipe para copiar para área de transferência"> &raquo; {{ resultado.url|urlizetrunc:40 }}
            </li>
            {% else %}
            <li class="error">{{ resultado.mensagem }}</li>
            {% endifequal %}
        </ul>
        {% else %}
            <h3 style="color:darkblue">Faça o login ou cadastre-se para gerar links encurtados.</h3>
        {% endif %}
    </div>
{% endblock %}

<script src="{% static 'encurtador/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'encurtador/zeroclipboard/ZeroClipboard.js' %}" type="text/javascript"></script>
<script type="text/javascript">
select_text = function(){
    input_text = '#shortened-urls li input';
    ZeroClipboard.setMoviePath("{% static 'encurtador/css/home.css' %}encurtador/zeroclipboard/ZeroClipboard.swf");
    var clip = new ZeroClipboard.Client(input_text);

    clip.on('noflash', function (client) {
        $(input_text).prop('title', '');
    });

    clip.on('complete', function (client, args) {
        $(".clipboard-info").show().html("Copiado para área de transferência: " + args.text);
    });

    $(input_text).bind("mouseover", function(){
        clip.setText($(this).attr('data-clipboard-text'));
    });
}

shorten_url = function(url){
    truncate = function(text){
        if(text.length > 40){
            text = text.substr(0, 40) + '...'
        }
        return text
    }
    $.ajax({
        type: "POST",
        url: "{% url home %}",
        cache: false,
        data: $('#form-shorten-url form').serialize(),
        dataType:'json',
        success: function(data){
            if (data.status == 'ok') {
                container = $('#shortened-urls');
                container.show().addClass('ok');
                html = '<li class="short-url">';
                html += '<span class="select-text" data-shortened-url="';
                html += data.url_curta;
                html += '">selecionar</span>';
                html += ' - <input type="text" data-clipboard-text="';
                html += data.url_curta;
                html += '" href="';
                html += data.url_curta;
                html += '" value="';
                html += data.url_curta;
                html += '" title="Clipe para copiar para área de transferência">';
                html += ' &raquo;';
                html += '<a href="';
                html += data.url;
                html += '">';
                html += truncate(data.url);
                html += '</a>';
                html += '</li>';
                container.prepend(html);
                $('#id_url').val('');
                select_text();
            }else{
                alert('Entre com uma URL válida para ser encurtada!')
            }
        }
    });
}
$(document).ready(function(){
    $("#shorten-it").click(function(){
        val = $('#id_url').val();
        if (val) {
            shorten_url(val);
        }else{
            alert('Entre com uma URL válida para ser encurtada!')
        }
        return false;
    });
    select_text();
});
</script>

encurtador/templates/encurtador/my-links.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="{{ STATIC_URL }}encurtador/css/my-links.css" type="text/css">

{% block conteudo %}
    <div id="my-links-container">
        <h1>Meus Links <small class="clipboard-info"></small></h1>
        {% if user.is_authenticated %}
            {% if meus_links %}
                {% include 'global-pagination.html' %}
                <ul id="my-links">
                {% for l in meus_links %}
                    <li>
                        [{{ l.criacao }}] - <input type="text" data-clipboard-text="{{ l.url_curta }}" value="{{ l.url_curta }}" title="Clipe para copiar para área de transferência"> &raquo; {{ l.url|urlizetrunc:50 }}
                    </li>
                {% endfor %}
                </ul>
                {% include 'global-pagination.html' %}
            {% else %}
                <p class="warning">Você ainda não possui links para serem exibidos!</p>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

<!--<script src="{{ STATIC_URL }}encurtador/js/jquery.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}encurtador/zeroclipboard/ZeroClipboard.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    input_text = '#my-links li input';
    ZeroClipboard.setMoviePath("{{ STATIC_URL }}encurtador/zeroclipboard/ZeroClipboard.swf");
    var clip = new ZeroClipboard.Client(input_text);

    clip.on('noflash', function (client) {
        $(input_text).prop('title', '');
    });

    clip.on('complete', function (client, args) {
        $(".clipboard-info").show().html("Copiado para área de transferência: " + args.text);
    });

    $(input_text).bind("mouseover", function(){
        clip.setText($(this).attr('data-clipboard-text'));
    });
});
</script>-->


<script src="{% static 'encurtador/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'encurtador/zeroclipboard/ZeroClipboard.js' %}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    input_text = '#my-links li input';
    ZeroClipboard.setMoviePath("{% static 'encurtador/zeroclipboard/ZeroClipboard.swf' %}");
    var clip = new ZeroClipboard.Client(input_text);

    clip.on('noflash', function (client) {
        $(input_text).prop('title', '');
    });

    clip.on('complete', function (client, args) {
        $(".clipboard-info").show().html("Copiado para área de transferência: " + args.text);
    });

    $(input_text).bind("mouseover", function(){
        clip.setText($(this).attr('data-clipboard-text'));
    });
});
</script>