encurtador_de_link/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('encurtador.urls')),
    path('perfil/', include('perfil.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/urls.py
  
from django.urls import path, re_path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('acessos/', views.ProgressaoAcesso.as_view(), name='acessos'),
    # re_path(r'^pdf/$', views.GenerateRelatorioPdfAcessos.as_view(), name="relatorio"),
    path('relatorio/', views.GenerateRelatorioPdfAcessos.as_view(), name="relatorio"),
]

perfil/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError

import re
from utils.validacpf import valida_cpf


class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE,
                                   verbose_name='Usuário')
    idade = models.PositiveIntegerField()
    data_nascimento = models.DateField()
    cpf = models.CharField(max_length=11)
    endereco = models.CharField(max_length=50)
    numero = models.CharField(max_length=5)
    complemento = models.CharField(max_length=30)
    bairro = models.CharField(max_length=30)
    cep = models.CharField(max_length=8)
    cidade = models.CharField(max_length=30)
    estado = models.CharField(
        max_length=2,
        default='SP',
        choices=(
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )

    acessos = models.PositiveIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return f'{self.usuario}'
    
    def get_acessos(self):
        self.acessos += 1
        return self.acessos

    def clean(self):
        error_messages = {}

        cpf_enviado = self.cpf or None
        cpf_salvo = None
        perfil = Perfil.objects.filter(cpf=cpf_enviado).first()

        if perfil:
            cpf_salvo = perfil.cpf

            if cpf_salvo is not None and self.pk != perfil.pk:
                error_messages['cpf'] = 'CPF já existe.'

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Digite um CPF válido'

        if re.search(r'[^0-9]', self.cep) or len(self.cep) < 8:
            error_messages['cep'] = 'CEP inválido, digite os 8 digitos do CEP.'

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class PerfilForm(forms.ModelForm):
    class Meta:
        model = models.Perfil
        fields = '__all__'
        exclude = ('usuario', 'acessos')


class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha',
    )

    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmação senha'
    )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.usuario = usuario

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password',
                  'password2', 'email')

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        usuario_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password2_data = cleaned.get('password2')

        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'E-mail já existe'
        error_msg_password_match = 'As duas senhas não conferem'
        error_msg_password_short = 'Sua senha precisa de pelo menos 6 caracteres'
        error_msg_required_field = 'Este campo é obrigatório.'

        # Usuários logados: atualização
        if self.usuario:
            if usuario_db:
                if usuario_data != usuario_db.username:
                    validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                if email_data != email_db.email:
                    validation_error_msgs['email'] = error_msg_email_exists

            if password_data:
                if password_data != password2_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password2'] = error_msg_password_match

                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_short

        # Usuários não logados: cadastro
        else:
            if usuario_db:
                validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                validation_error_msgs['email'] = error_msg_email_exists

            if not password_data:
                validation_error_msgs['password'] = error_msg_required_field

            if not password2_data:
                validation_error_msgs['password2'] = error_msg_required_field

            if password_data != password2_data:
                validation_error_msgs['password'] = error_msg_password_match
                validation_error_msgs['password2'] = error_msg_password_match

            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short

        if validation_error_msgs:
            raise(forms.ValidationError(validation_error_msgs))

perfil/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views import View
from django.http import HttpResponseNotFound, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from django.urls import reverse_lazy

from perfil.models import Perfil
from perfil.forms import UserForm, PerfilForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# from perfil.utils import render_to_pdf

from django.contrib.auth.mixins import LoginRequiredMixin


class ProgressaoAcesso(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('perfil:criar')
    model = Perfil
    fields = ['usuario', 'acessos']
    template_name = 'perfil/acessos.html'
    success_url = reverse_lazy('acessos')  # listar-progressao

    def form_valid(self, form):

        # Antes do super não foi criado o objeto nem salvo no banco
        form.instance.usuario = self.request.user

        url = super().form_valid(form)

        self.object.save()

        return url


# Gera relatorio pdf
class GenerateRelatorioPdfAcessos(View):
    """Gerar pdf de 'relatorio.html' de acessos."""
    def get(self, request, *args, **kwargs):
        context = {}
        usuario = request.user
        try:
            user_acessos = Perfil.objects.get(usuario=usuario)

        except Exception:
            return HttpResponseNotFound(
                            'Erro: <h1>Você é um Administrador</h1>')
        if user_acessos:
            context = {
                'acessos': user_acessos.acessos
            }
            # pdf = render_to_pdf('relatorio.html', context)

        else:
            return HttpResponseNotFound('<h1>Page not found</h1>')
        # return HttpResponse(pdf, content_type='perfil/pdf')
        return render(request, "perfil/relatorio.html", context)


# Projeto encurtador de links com django
class LoginRequiredMixin(object):
    """
        Você pode conferir a explicação da criação desse Mixin em um post meu:
        http://douglasmiranda.com/artigo/login-required-mixin-django-class-based-generic-views-iv/
    """
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class BasePerfil(View):
    template_name = 'perfil/criar.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.perfil = None

        if self.request.user.is_authenticated:
            self.perfil = Perfil.objects.filter(
                usuario=self.request.user
            ).first()

            self.contexto = {
                'userform': UserForm(
                    data=self.request.POST or None,
                    usuario=self.request.user,
                    instance=self.request.user,
                ),
                'perfilform': PerfilForm(
                    data=self.request.POST or None,
                    instance=self.perfil
                )
            }
        else:
            self.contexto = {
                'userform': UserForm(
                    data=self.request.POST or None
                ),
                'perfilform': PerfilForm(
                    data=self.request.POST or None
                )
            }

        self.userform = self.contexto['userform']
        self.perfilform = self.contexto['perfilform']

        if self.request.user.is_authenticated:
            self.template_name = 'perfil/atualizar.html'

        self.renderizar = render(
            self.request, self.template_name, self.contexto)

    def get(self, *args, **kwargs):
        return self.renderizar


class Criar(BasePerfil):
    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.perfilform.is_valid():
            messages.error(
                self.request,
                'Existem erros no formulário de cadastro. Verifique se todos '
                'os campos foram preenchidos corretamente.'
            )

            return self.renderizar

        username = self.userform.cleaned_data.get('username')
        password = self.userform.cleaned_data.get('password')
        email = self.userform.cleaned_data.get('email')
        first_name = self.userform.cleaned_data.get('first_name')
        last_name = self.userform.cleaned_data.get('last_name')

        # Usuário logado - alterações
        if self.request.user.is_authenticated:
            usuario = get_object_or_404(
                User, username=self.request.user.username)

            usuario.username = username

            if password:
                usuario.set_password(password)

            usuario.email = email
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.save()

            if not self.perfil:
                self.perfilform.cleaned_data['usuario'] = usuario
                print(self.perfilform.cleaned_data)
                perfil = Perfil(**self.perfilform.cleaned_data)
                perfil.save()
            else:
                perfil = self.perfilform.save(commit=False)
                perfil.usuario = usuario
                perfil.acessos += 1
                perfil.save()

        # Usário não logado (novo)
        else:
            usuario = self.userform.save(commit=False)
            usuario.set_password(password)
            usuario.save()

            perfil = self.perfilform.save(commit=False)
            perfil.usuario = usuario
            perfil.save()

        if password:
            autentica = authenticate(
                self.request,
                username=usuario,
                password=password
            )

            if autentica:
                login(self.request, user=usuario)

        self.request.session.save()

        messages.success(
            self.request,
            'Seu cadastro foi criado ou atualizado com sucesso.'
        )

        messages.success(
            self.request,
            'Você fez login.'
        )

        return redirect('/')


class Atualizar(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Atualizar')


class Login(View):
    def post(self, request, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')
        try:
            if not username or not password:
                messages.error(
                    self.request,
                    'Usuário ou senha inválidos.'
                )
                return redirect('perfil:criar')

            usuario = authenticate(
                self.request, username=username, password=password)
            if usuario:
                # Contador acessos de login do user
                user_acessos = Perfil.objects.get(usuario=usuario)
                user_acessos.acessos += 1
                user_acessos.save()

            if not usuario:
                messages.error(
                    self.request,
                    'Usuário ou senha inválidos.'
                )
                return redirect('perfil:criar')

        except Exception:
            return HttpResponseNotFound(
                            '''Erro: <h1>Você é um Administrador</h1>
                               Entre com um usuário comum.''')
        login(self.request, user=usuario)

        messages.success(
            self.request,
            'Você está logado no sistema.'
        )

        return redirect('/')


class Logout(View):
    def get(self, *args, **kwargs):

        logout(self.request)

        self.request.session.save()

        return redirect('/')

perfil/templates/perfil/acessos.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Acessos | {% endblock %}

{% block conteudo %}

<h2>Acessos</h2>

<div class="row">
    
    {% if request.user.is_authenticated %}
        <div>
            <p>Usuário: {{ user }}</p>
        </div>
        <div class="container">
            <a class="btn btn-outline-info" href="{% url 'perfil:relatorio' %}">
                Gerar Relatório
            </a>
        </div>

    {% else %}
        <h4>Faça o login para ver os acessos</h4>
    {% endif %}

</div>

{% endblock %}

perfil/templates/perfil/atualizar.html
{% extends 'perfil/criar.html' %}

{% block titulo %}Atualizar perfil de {{ user }} | {% endblock %}

{% block titulocadastro %}
<h4>Atualizar cadastro</h4>
<p>
    Utilize o formulário a seguir para atualizar seus dados.
</p>
{% endblock %}

perfil/templates/perfil/criar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Criar perfil | {% endblock %}

{% block conteudo %}

<div class="row">

    {% if not request.user.is_authenticated %}
    <div class="col-lg mt-3">
        <h4>Login</h4>
        <p>Se você já fez cadastro, basta entrar com seu usuário e senha abaixo:</p>

        <form method="POST" action="{% url 'perfil:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="InputUsuario1">Usuário</label>
                <input type="text" name='username' class="form-control" id="InputUsuario1"
                    aria-describedby="usuarioHelp" placeholder="Digite seu usuário">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Senha:</label>
                <input name='password' type="password" class="form-control" id="exampleInputPassword1"
                    placeholder="Digite sua senha">
            </div>
            <button type="submit" class="btn btn-primary btn-block btn-lg">Entrar</button>
        </form>


    </div>
    {% endif %}

    <div class="col-lg mt-3">

        {% block titulocadastro %}
        <h4>Cadastro</h4>
        <p>
            Caso ainda não tenha cadastro, utilize o formulário a seguir para se
            cadastrar.
        </p>
        <p>
            Os dados inseridos por si neste formulário serão usados única e exclusivamente para futuros contatos e não serão guardados em base de dados nem disponibilizados a terceiros.
        </p>
        {% endblock %}

        <form method="POST" action="">
            {% csrf_token %}
            {{ userform|crispy }}
            {{ perfilform|crispy }}

            <div class="row">
                <div class="col">
                    <button type="submit" class='btn btn-primary btn-block btn-lg'>
                        Enviar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

perfil/templates/perfil/form.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h3>{{ titulo }}</h3>

<p class="lead">
    Preencha todos os campos obrigatórios.
</p>

<hr>

<form action="" method="POST">

    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-light mt-3">
        {% autoescape off %}
        {{ icone }}
        {% endautoescape %}
        {{ botao }}
    </button>

</form>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){

        $("#id_cpf").mask("000.000.000-00");
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);


    });
</script>
{% endblock %}

perfil/templates/perfil/relatorio.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Acessos | {% endblock %}

{% block conteudo %}

<h2>Acessos</h2>

<div class="row">
    
    {% if request.user.is_authenticated %}

    <div class='wrapper'>
        <div class='header'>
        <p class='title'>Relatório de número de acessos no login do sistema.</p>
        </div>
        <div class='details'>
            Data: {% now "d/m/Y" %} <br>
            Usuário: {{ user }} <br>
            <hr class='hrItem' />
        </div>

        <div>
            <label>Número de acessos no login do sistema:
            {{ acessos }}
            </label>
        </div>

    </div>

    {% else %}
        <h4>Faça o login para ver os acessos</h4>
    {% endif %}

    <div class="col-lg mt-3">

    </div>
</div>

{% endblock %}


<!--<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Retatório de número de acessos</title>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
         {load my_filters}
        
        <div class='wrapper'>
            <div class='header'>
		    <p class='title'>Relatório de número de acessos separado por dia da semana.</p>
            </div>
            <div class='details'>
                Data: {% now "jS F Y H:i" %} <br>
                Usuário: {{ usuario.nome }} <br>
                <hr class='hrItem' />
            </div>
            <div class="pure-u-1">
                <table class="pure-table pure-table-bordered">
                    <thead>
                    <tr>
                        <th>Dia</th>
                        <th>Data e hora</th>
                        <th>Usuário</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for u in usuario %}
                    <tr style="text-align: center;">
                        <td>{{ u.dia }}</td>
                        <td>{{ u.data_hora }}</td>
                        <td>{{ u.usuario }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <hr class='hrItem' />
                <table class="pure-table pure-table-bordered">
                    <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr style="text-align: center;">
                        <td></td>
                        <td></td>
                        <td></td>

                    </tr>
                    </tbody>
                </table>

            </div>
            <div class='details'>
                <hr class='hrItem' />
            </div>
        </div>
    </body>
</html>-->