encurtador/urls.py
from django.urls import path, re_path
from . import views

app_name = 'encurtador'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    re_path(r'^(?P<uuid_curto>[\-\d\w]+)$',
                    views.GoToRedirectView.as_view()),

    path('my-links/',
                    views.MyLinksListView.as_view(), name='my_links'),
]

encurtador_de_link/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('encurtador.urls')),
    path('perfil/', include('perfil.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/urls.py
  
from django.urls import path, re_path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('acessos/', views.ProgressaoAcesso.as_view(), name='acessos'),
    # re_path(r'^pdf/$', views.GenerateRelatorioPdfAcessos.as_view(), name="relatorio"),
    path('relatorio/', views.GenerateRelatorioPdfAcessos.as_view(), name="relatorio"),
]

templates/parciais/_footer.html
{% load static %}


<footer class="border-top text-muted bg-light">
    <div class="container">
        <div class="row py-3">
            <div class="col-12 col-md-4 text-center">
                &copy; 2021 - Encurtador de Link
            </div>

            <div class="col-12 col-md-4 text-center">
                <a href="https://github.com/CesarAugusto88/desafio_tecnico#readme" class="text-decoration-none text-dark">
                    <span class="align-middle p-1">Todos os Créditos no Readme do projeto</span>
                </a>
            </div>

            <div class="col-12 col-md-4 text-center">
                <span class="align-middle p-1">Por Cesar Augusto</span> <br>
                <span class="align-middle p-1">Feito com Django</span>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
<!-- <nav class="navbar navbar-dark bg-primary navbar-expand-lg"> -->
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="{% url 'encurtador:home' %}">Encurtador de Link</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'perfil:criar' %}">Login</a>
                <a class="nav-link" aria-current="page" href="{% url 'encurtador:my_links' %}">Meus Links</a>
                <a class="nav-link" aria-current="page" href="{% url 'perfil:acessos' %}">Acessos</a>
                <a class="nav-link" href="{% url 'perfil:logout' %}">Logout</a>
              </div>

        </ul>

    </div>
</nav>